// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'description': string;
  'done': string;
  'link_block': string;
  'project_name': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
