// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'another': string;
  'block': string;
  'content': string;
  'current': string;
  'description': string;
  'done': string;
  'gallery': string;
  'next': string;
  'previous': string;
  'project_name': string;
  'root': string;
  'to_next': string;
  'to_prew': string;
}
export const cssExports: CssExports;
export default cssExports;
