// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'git': string;
  'linkedin': string;
  'mail': string;
  'phone': string;
  'root': string;
  'telegram': string;
}
export const cssExports: CssExports;
export default cssExports;
