// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'close_button': string;
  'description': string;
  'img_container': string;
  'not_deployed': string;
  'pdf_closed': string;
  'pdf_opened': string;
  'project': string;
  'projects': string;
  'show_button': string;
}
export const cssExports: CssExports;
export default cssExports;
