// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'avatar_img': string;
  'burger': string;
  'close_burg': string;
  'container': string;
  'current_link': string;
  'link': string;
  'links': string;
  'open': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
